### ISSUE TITLE
py3.x/ml/7.RandomForest/randomForest.py : TypeError: '<' not supported between instances of 'float' and 'str'

### ISSUE THREAD

**Issue by MacleZhou** [apachecn/AiLearning#570]
/usr/local/bin/python3.7 /Users/maclezhou/AI/apachecn/AiLearning/src/py3.x/ml/7.RandomForest/randomForest.py
Traceback (most recent call last):
  File "/Users/maclezhou/AI/apachecn/AiLearning/src/py3.x/ml/7.RandomForest/randomForest.py", line 322, in <module>
    scores = evaluate_algorithm(dataset, random_forest, n_folds, max_depth, min_size, sample_size, n_trees, n_features)
  File "/Users/maclezhou/AI/apachecn/AiLearning/src/py3.x/ml/7.RandomForest/randomForest.py", line 300, in evaluate_algorithm
    predicted = algorithm(train_set, test_set, *args)
  File "/Users/maclezhou/AI/apachecn/AiLearning/src/py3.x/ml/7.RandomForest/randomForest.py", line 244, in random_forest
    tree = build_tree(sample, max_depth, min_size, n_features)
  File "/Users/maclezhou/AI/apachecn/AiLearning/src/py3.x/ml/7.RandomForest/randomForest.py", line 162, in build_tree
    root = get_split(train, n_features)
  File "/Users/maclezhou/AI/apachecn/AiLearning/src/py3.x/ml/7.RandomForest/randomForest.py", line 107, in get_split
    groups = test_split(index, row[index], dataset)  # groups=(left, right), row[index] 遍历每一行 index 索引下的特征值作为分类值 value, 找出最优的分类特征和特征值
  File "/Users/maclezhou/AI/apachecn/AiLearning/src/py3.x/ml/7.RandomForest/randomForest.py", line 76, in test_split
    if row[index] < value:
**TypeError: '<' not supported between instances of 'float' and 'str'**

Process finished with exit code 1

**Comment by jiangzhonglian** [comment]
可以修改一下数据类型： if float(row[index]) < float(value):

* 主要是针对 2.x => 2.7 版本，学习运行版本；
* 3.x 版本我们没做太多的修改，考验你的编码能力，需要修改API的版本语法；

**Comment by MacleZhou** [comment]
Thank you!
